server:
  port: 9081

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:9432/calorie_tracker
    username: calorie_user
    password: calorie_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
